// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6W_7rDZyu_idLEeKnsVyeXcqLk3CsWZo',
    appId: '1:778994165396:web:5910b05dae9b0d9f187681',
    messagingSenderId: '778994165396',
    projectId: 'qrscannergklcl',
    authDomain: 'qrscannergklcl.firebaseapp.com',
    databaseURL: 'https://qrscannergklcl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrscannergklcl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6810M-iKcRgRhcQ_8DvmRb12c3G9_HNw',
    appId: '1:778994165396:android:f1c455aedc673a5e187681',
    messagingSenderId: '778994165396',
    projectId: 'qrscannergklcl',
    databaseURL: 'https://qrscannergklcl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrscannergklcl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUBpyqAfCkGQsniXsFHuJZxxY7sLXFVk',
    appId: '1:778994165396:ios:ef370d002237ace5187681',
    messagingSenderId: '778994165396',
    projectId: 'qrscannergklcl',
    databaseURL: 'https://qrscannergklcl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrscannergklcl.appspot.com',
    iosClientId: '778994165396-79bvcb2v3s46e8nu4jejocck4fo15mbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.qr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUBpyqAfCkGQsniXsFHuJZxxY7sLXFVk',
    appId: '1:778994165396:ios:ef370d002237ace5187681',
    messagingSenderId: '778994165396',
    projectId: 'qrscannergklcl',
    databaseURL: 'https://qrscannergklcl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrscannergklcl.appspot.com',
    iosClientId: '778994165396-79bvcb2v3s46e8nu4jejocck4fo15mbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.qr',
  );
}
